#encoding: UTF-8

spanish = {
'lang': 'Español',
'button_ok': 'Aceptar',
'button_cancel': 'Cancelar',
'button_open': 'Abrir',
'button_save': 'Guardar',
'button_saveAs': 'Guardar como...',
'button_newTag': 'Nuevo Tag',
'button_newChildTag': 'Nuevo Child',
'button_copyTag': 'Copiar Tag',
'button_deleteTag': 'Borrar Tag',
'button_glTreeView': 'Chequea árbol',
'button_analyze': 'Imprime band_buttons',
'button_captureStringXML': 'Imprime elemento en text',
'button_dicSubnames': 'Imprime dicSubnames',
'button_getDicSubnames': 'Consigue Subnames',
'button_printEncoding': 'Encodeo',
'button_printPrettyPrint': 'PrettyPrint', 
'button_printIDTagInTree': 'ID TagInTree', 
'button_showCurrentSearch': 'Busqueda Actual', 
'button_showXMLParentMap': 'Mostrar Parent Map', 
'button_showDicTagsInTree': 'Mostrar DicTagsInTree', 
'button_showCaseSensitive': 'Mostrar dist. mayús',
'button_moveUp': 'Mover Tag arriba',
'button_moveDown': 'Mover Tag abajo',
'button_moveBeginnnig': 'Mover Tag inicio',
'button_moveEnd': 'Mover Tag final',
'column-data': 'Datos',
'column-name': 'Nombre',
'column-size': 'Tamaño',
'frame_search': 'Búsqueda',
'menu_config': 'Configuración',
'menu_config_language': 'Lenguaje',
'menu_config_language_spa': 'Español',
'menu_config_language_eng': 'Inglés',
'menu_config_printmode': 'Impresión', 
'menu_config_printmode_prettyprint': 'Guardar con Formato', 
'menu_config_printmode_nospaceclosedtag': 'Sin espacios en Tag cerrado',  
'menu_config_search': 'Búsquedas',
'menu_config_search_caseSensitive': 'Distingue mayúsculas',
'menu_file': 'Archivo',
'menu_file_open': 'Abrir',
'menu_file_save': 'Guardar',
'menu_file_saveas': 'Guardar como...',
'menu_file_exit': 'Salir',
'message_exitsave': 'El archivo %s se ha modificado. Desea guardar los cambios?',
'message_newtag': 'Nuevo Tag',
'message_edittag': 'Editar Tag',
'message_editing': 'Editando', 
'message_value': 'Valor', 
'option_tags': 'Tags',
'option_values': 'Valores',
'submenu_selectParentSubname': 'Seleccionar como Subnombre del Parent',
'submenu_cleanParentSubname': 'Limpiar definición de Subnombre',
'submenu_edittag': 'Editar Tag',
'submenu_copytag': 'Copiar Tag a Portapapeles',
}

english = {
'lang': 'English',
'button_ok': 'Ok',
'button_cancel': 'Cancel',
'button_open': 'Open',
'button_save': 'Save',
'button_saveAs': 'Save as...',
'button_newTag': 'New Tag',
'button_newChildTag': 'New Child',
'button_copyTag': 'Copy Tag',
'button_deleteTag': 'Delete Tag',
'button_glTreeView': 'Check Treeview',
'button_analyze': 'Print band_buttons',
'button_captureStringXML': 'Print StringXML',
'button_dicSubnames': 'Print dicSubnames',
'button_getDicSubnames': 'Get dicSubnames',
'button_printEncoding': 'Print encoding',
'button_printPrettyPrint': 'PrettyPrint', 
'button_printIDTagInTree': 'ID TagInTree', 
'button_showCurrentSearch': 'Current search', 
'button_showXMLParentMap': 'Show Parent Map',
'button_showDicTagsInTree': 'Show DicTagsInTree', 
'button_showCaseSensitive': 'Show Case Sensitive',
'button_moveUp': 'Move Tag up',
'button_moveDown': 'Move Tag down',
'button_moveBeginnnig': 'Move Tag first',
'button_moveEnd': 'Move Tag last',
'column-data': 'Data',
'column-name': 'Name',
'column-size': 'Size',
'frame_search': 'Search',
'menu_config': 'Configuration',
'menu_config_language': 'Language',
'menu_config_language_spa': 'Spanish',
'menu_config_language_eng': 'English',
'menu_config_printmode': 'Printing', 
'menu_config_printmode_prettyprint': 'Pretty Print', 
'menu_config_printmode_nospaceclosedtag': 'No spaces in closed Tag', 
'menu_config_search': 'Search',
'menu_config_search_caseSensitive': 'Case Sensitive',
'menu_file': 'File',
'menu_file_open': 'Open',
'menu_file_save': 'Save',
'menu_file_saveas': 'Save as...',
'menu_file_exit': 'Exit',
'message_exitsave': 'The file %s has changed. Do you want to save?',
'message_newtag': 'New Tag',
'message_edittag': 'Edit Tag',
'message_editing': 'Editing', 
'message_value': 'Value', 
'option_tags': 'Tags',
'option_values': 'Values',
'submenu_selectParentSubname': 'Select as parent subname',
'submenu_cleanParentSubname': 'Clean subname definition',
'submenu_edittag': 'Edit Tag',
'submenu_copytag': 'Copy Tag to Clipboard',
}