#encoding: UTF-8

spanish = {
'lang': 'Español',
'button_open': 'Abrir',
'button_save': 'Guardar',
'button_saveAs': 'Guardar como...',
'button_copyTag': 'Copiar Tag',
'button_deleteTag': 'Borrar Tag',
'button_glTreeView': 'Chequea árbol',
'button_analyze': 'Imprime band_buttons',
'button_dicSubnames': 'Imprime dicSubnames',
'button_getDicSubnames': 'Consigue Subnames',
'button_printEncoding': 'Encodeo',
'button_moveUp': 'Mover Tag arriba',
'button_moveDown': 'Mover Tag abajo',
'button_moveBeginnnig': 'Mover Tag inicio',
'button_moveEnd': 'Mover Tag final',
'column-data': 'Datos',
'column-name': 'Nombre',
'column-size': 'Tamaño',
'menu_config': 'Configuración',
'menu_config_language': 'Lenguaje',
'menu_config_language_spa': 'Español',
'menu_config_language_eng': 'Inglés',
'menu_file': 'Archivo',
'menu_file_open': 'Abrir',
'menu_file_save': 'Guardar',
'menu_file_saveas': 'Guardar como...',
'menu_file_exit': 'Salir',
'submenu-selectParentSubname': 'Seleccionar como Subnombre del Parent',
'submenu-cleanParentSubname': 'Limpiar definición de Subnombre',
}

english = {
'lang': 'English',
'button_open': 'Open',
'button_save': 'Save',
'button_saveAs': 'Save as...',
'button_copyTag': 'Copy Tag',
'button_deleteTag': 'Delete Tag',
'button_glTreeView': 'Check Treeview',
'button_analyze': 'Print band_buttons',
'button_dicSubnames': 'Print dicSubnames',
'button_getDicSubnames': 'Get dicSubnames',
'button_printEncoding': 'Print encoding',
'button_moveUp': 'Move Tag up',
'button_moveDown': 'Move Tag down',
'button_moveBeginnnig': 'Move Tag beginning',
'button_moveEnd': 'Move Tag end',
'column-data': 'Data',
'column-name': 'Name',
'column-size': 'Size',
'menu_config': 'Configuration',
'menu_config_language': 'Language',
'menu_config_language_spa': 'Spanish',
'menu_config_language_eng': 'English',
'menu_file': 'File',
'menu_file_open': 'Open',
'menu_file_save': 'Save',
'menu_file_saveas': 'Save as...',
'menu_file_exit': 'Exit',
'submenu-selectParentSubname': 'Select as parent subname',
'submenu-cleanParentSubname': 'Clean subname definition',
}
